object Versions {
    // Libs versions
    const val coreKtx_version = "1.9.0"
    const val appcompat_version = "1.5.1"
    const val material_version = "1.7.0"
    const val constraintLayout_version = "2.1.4"
    const val koin_version = "2.2.3"
    const val lifecycle_version = "2.5.1"
    const val fragment_version = "1.6.0-alpha04"
    const val gson_version = "2.9.0"
    const val okhttp_version = "4.9.0"
    const val retrofit_version = "2.9.0"
    const val coroutines_version = "1.6.4"
    const val annotation_version = "1.4.0"
    const val glide_version = "4.13.2"
    const val glide_transformation_version = "4.3.0"
    const val lottie_version = "5.2.0"
    const val rxjava_version = "2.2.17"
    const val rxAndroid_version = "2.1.1"
    const val detekt_version = "1.22.0"
    const val jacoco_version = "0.8.6"
    const val swipeRefresh_version = "1.1.0"
    const val timber_version = "4.7.1"

    // Tests Libs versions
    const val junit_version = "4.13.2"
    const val androidxJunit_version = "1.1.3"
    const val espresso_version = "3.4.0"
    const val mockk_version = "1.11.0"
    const val turbine_version = "0.8.0"
    const val testRules_version = "1.3.0"
    const val kotlin_version = "1.7.20"
    const val coreTest_version = "2.1.0"
    const val mockWebserver_version = "4.9.0"
    const val okhttpTest_version = "4.9.0"
}
